mem(1)

# NAME
mem - a utility to display memory information 

# SYNOPSIS

usage: *mem* [-utfh]

Default is *-h*

# OPTIONS

*-h*
	Show help message and quit.
*-u*
	Show used memory and quit.
*-t*
	Show total memory and quit.
*-f*
	Show free memory and quit.

# DESCRIPTION

*mem* was made to fill the need of a utility that could be used in shell scripts/ or in a desktop bar, such as swaybar.

# AUTHORS
utools author - moatx (_spelled lowercase_)
