power(1)

# NAME
power - a utility to display power information

# SYNOPSIS

usage: *power* [-cph]

Default is *-c*

# OPTIONS

*-h*
	Show help message and quit.
*-c*
	Show yes or no on whether it's charging and quit.
*-p*
	Show power capacity and quit.

# DESCRIPTION

power was created to fill the need of a utility that could be used in shell scripts/ or in a desktop bar, such as swaybar

# AUTHORS
utools author - moatx (_spelled lowercase_)
